# Generated by Django 4.1.3 on 2023-02-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=255)),
                ("Type", models.CharField(max_length=255)),
                ("Quantity", models.IntegerField()),
                ("Units", models.CharField(max_length=3)),
                ("Description", models.CharField(max_length=255)),
                ("Comments", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="permissions",
            fields=[
                (
                    "role",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("metrics", models.CharField(blank=True, max_length=255, null=True)),
                ("network", models.CharField(blank=True, max_length=10, null=True)),
                ("readwrite", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "permissions",
            },
        ),
        migrations.AlterModelTable(
            name="users",
            table="users",
        ),
    ]
