# Generated by Django 4.1.3 on 2023-02-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comments_permissions_alter_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Quantity', models.IntegerField()),
                ('Units', models.CharField(max_length=3)),
                ('Description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
