# Generated by Django 4.1.3 on 2023-02-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_posts"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comments",
            table=None,
        ),
    ]
