# Generated by Django 4.1.3 on 2023-02-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_posts"),
    ]

    operations = [
        migrations.CreateModel(
            name="tracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(max_length=255)),
                ("Description", models.CharField(max_length=255)),
                ("Quantity", models.IntegerField(max_length=55)),
                ("Qunits", models.CharField(max_length=255)),
                ("amountToClients", models.IntegerField(max_length=55)),
                ("amountToAFeed", models.IntegerField(max_length=55)),
                ("amountToCompost", models.IntegerField(max_length=55)),
                ("amountToPartNet", models.IntegerField(max_length=55)),
                ("amountToLandfill", models.IntegerField(max_length=55)),
                ("percentClients", models.IntegerField(max_length=55)),
                ("percentAFeed", models.IntegerField(max_length=55)),
                ("percentCompost", models.IntegerField(max_length=55)),
                ("percentPartNet", models.IntegerField(max_length=55)),
                ("percentLandfill", models.IntegerField(max_length=55)),
            ],
            options={"db_table": "tracker",},
        ),
        migrations.RemoveField(model_name="posts", name="id",),
        migrations.AlterField(
            model_name="posts",
            name="product",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
