# Generated by Django 4.1.3 on 2023-02-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_comments_table"),
        ("api", "0004_tracker_remove_posts_id_alter_posts_product"),
    ]

    operations = []
