# Generated by Django 4.1.3 on 2023-02-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_merge_20230215_1750"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="comments",
            table="comments",
        ),
    ]
