# Generated by Django 4.1.3 on 2022-11-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodsaviour", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="Email",
            field=models.EmailField(max_length=254),
        ),
    ]
