# Generated by Django 4.1.3 on 2022-11-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodsaviour", "0002_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users", name="Email", field=models.CharField(max_length=255),
        ),
    ]
