# Generated by Django 4.1.2 on 2022-11-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodsaviour", "0003_alter_users_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="Organization",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
