# Generated by Django 4.1.2 on 2022-11-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FirstName", models.CharField(max_length=255)),
                ("LastName", models.CharField(max_length=255)),
                ("Email", models.CharField(max_length=255)),
                ("Password", models.CharField(max_length=255)),
                ("Roles", models.CharField(max_length=255)),
                ("Consent", models.CharField(max_length=50)),
                ("Organization", models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
