# Generated by Django 4.1.3 on 2022-11-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postlogin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="Approve",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
