# Generated by Django 4.1.3 on 2022-11-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postlogin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Description", models.CharField(max_length=255)),
                ("Category", models.CharField(max_length=255)),
                ("Quantity", models.PositiveIntegerField()),
                ("Qunits", models.CharField(max_length=255)),
                ("DivertClients", models.PositiveIntegerField()),
                ("DivertAFeed", models.PositiveIntegerField()),
                ("DivertCompost", models.PositiveIntegerField()),
                ("DivertPartNet", models.PositiveIntegerField()),
                ("DivertLandfill", models.PositiveIntegerField()),
            ],
        ),
    ]
