# Generated by Django 4.1.3 on 2022-11-22 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postlogin", "0002_inventory"),
        ("postlogin", "0002_users_approve"),
    ]

    operations = []
