# Generated by Django 4.1.2 on 2022-11-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postlogin", "0003_merge_0002_inventory_0002_users_approve"),
    ]

    operations = [
        migrations.CreateModel(
            name="permissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Role", models.CharField(max_length=255)),
                ("Metrics", models.CharField(max_length=255)),
                ("Network", models.CharField(max_length=255)),
                ("readwrite", models.CharField(max_length=255)),
            ],
        ),
    ]
