name: Test

on:
  pull_request:
    branches:
      - code
      - develop

jobs:
  backend:
    name: Test backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test backend
      run: |
        source env/bin/activate
        cd backend/
        python manage.py test

  frontend:
    name: Test frontend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: |
        cd frontend/
        npm install
    - name: Test frontend
      run: |
        cd frontend/
        npm run test
